#! /bin/bash
# Requirements: curl, tidy, figlet
clear
# Variables
URL="http://api.bart.gov/api/"
KEY="MW9S-E7SL-26DU-VV8V"
ADVISORIES="bsa.aspx?cmd=bsa&key="
ELEVATORS="bsa.aspx?cmd=elev&key="
TRAINS="bsa.aspx?cmd=count&key="
ORIG="etd.aspx?cmd=etd&orig=$2&key="
STNS="stn.aspx?cmd=stns&key="
FARE="sched.aspx?cmd=fare&orig=$2&dest=$3&key="
START=$2
END=$3

# Title
figlet "BART  Stats"

# Usage
if [ -z "$1" ]; then
  echo "Usage: ./bart-stats stationid"
  echo "Example: ./bart-stats 12th"
  exit
fi

# Advisories Information
echo ---------------------------------------------------
date
echo
echo -e "\e[4mAdvisory Information\e[24m"
echo -n "Advisories: "
curl --silent ${URL}${ADVISORIES}${KEY} | grep description | cut -d"[" -f3 | cut -d"]" -f1
echo -n "Elevator Information: "
curl --silent ${URL}${ELEVATORS}${KEY} | grep description | cut -d"[" -f3 | cut -d"]" -f1
echo -n "Trains in Service: "
curl --silent ${URL}${TRAINS}${KEY} | grep traincount | cut -d">" -f2 | cut -d"<" -f1
echo

# Functions
Fstationid(){
echo -e "\e[4mRealtime Information\e[24m"
echo -n "Estimated Time of Departure From Station: "
ETD=$(curl --silent -H "Accept: application/xml" -H "Content-Type: application/xml" -X GET ${URL}${ORIG}${KEY} | tidy -xml -quiet)
echo "$ETD" | grep name | cut -d">" -f2 | cut -d"<" -f1
printf "%31s Line | Departing In (minutes)\n"
for (( SELECT=1; SELECT<=$(echo "$ETD" | grep destination -c); SELECT++ ))
  do
    LINE=$(echo "$ETD" | grep destination | sed -n "$SELECT"p | cut -d">" -f2 | cut -d"<" -f1)
    TIME1=$(echo "$ETD" | grep destination -A 3 | grep minutes | sed -n "$SELECT"p | cut -d">" -f2 | cut -d"<" -f1)
    TIME2=$(echo "$ETD" | grep destination -A 12 | grep minutes | sed -n "$((SELECT*2))"p | cut -d">" -f2 | cut -d"<" -f1)
    TIME3=$(echo "$ETD" | grep destination -A 21 | grep minutes | sed -n "$((SELECT*3))"p | cut -d">" -f2 | cut -d"<" -f1)
    if [ -z "$TIME3" ] || [ "$TIME3" -le "$TIME2" ] || [ "$TIME3" = "Leaving" ]; then
      TIME3=$""
    fi
    if [ -z "$TIME2" ] || [ "$TIME2" -le "$TIME1" ] || [ "$TIME2" = "Leaving" ]; then
      TIME2=$""
    fi
    printf "$LINE %"$((35-${#LINE}))"s | $TIME1 %"$((7-${#TIME1}))"s $TIME2 %"$((7-${#TIME2}))"s $TIME3\n"
    #echo "$ETD" | grep destination -A 12
  done
echo
}

Ffare(){
echo -e "\e[4mFare\e[24m"
echo -n "From Station: "
curl --silent -H "Accept: application/xml" -H "Content-Type: application/xml" -X GET ${URL}${STNS}${KEY} | tidy -xml -quiet | grep -i -B 1 $START | grep name | cut -d">" -f2 | cut -d"<" -f1
echo -n "To Station:   "
curl --silent -H "Accept: application/xml" -H "Content-Type: application/xml" -X GET ${URL}${STNS}${KEY} | tidy -xml -quiet | grep -i -B 1 $END | grep name | cut -d">" -f2 | cut -d"<" -f1
echo -n "$"
curl --silent -H "Accept: application/xml" -H "Content-Type: application/xml" -X GET ${URL}${FARE}${KEY} | tidy -xml -quiet | grep "<fare>" | cut -d">" -f2 | cut -d"<" -f1
echo
}

case $1 in
  "stationid")
    Fstationid
    Ffare
    ;;
  "fare")
    Ffare
    ;;
  *)
  exit
  ;;
esac
